server:
    listen: 8080
    workers: 2
    upstreams:
        - id: jsonplaceholder
          url: jsonplaceholder.typicode.com

        - id: dummy
          url: dummyjson.com
    headers:
        - key: x-forward-for
          value: $ip
        - key: Authorization
          value: Bearer xyz

    rules:
        - path: /test
          upstreams:
              - dummy
        - path: /
          upstreams:
              - jsonplaceholder
